version: '3'

services:
  mountebank:
    image: jkris/mountebank:latest
    container_name: mountebank
    volumes:
      - ./templates:/templates
    ports:
      - 2525:2525
      - 8090:8090
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 8095:8095
      - 8096:8096
      - 8097:8097
    command: --configfile /templates/imposters.ejs --allowInjection